spring:
  application:
    name: bridge-spero
    storage:
      public-dir: static/uploads
      private-dir: uploads
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: false
    change-log: classpath:db/changelog-master.yaml
zoom:
  client-id: ${ZOOM_CLIENT_ID}
  client-secret: ${ZOOM_CLIENT_SECRET}
  redirect-uri: ${ZOOM_REDIRECT_URI}

application:
  security:
    authentication:
      jwt:
        base64-secret: ${JWT_SECRET}
        access-token-validity-in-seconds: 86400 # 1 day
        refresh-token-validity-in-seconds: 604800 # 1 week
  redis:
    address: redis://localhost:6379
    connection-pool-size: 4
    connection-minimum-idle-size: 2
    prefix: bs
    token-prefix: bs:token
    token-time-to-live: 604800
    zoom-token-prefix: bs:token:zoom
    zoom-token-time-to-live: 7776000  # 90 days
    zoom-state-prefix: bs:zoom:state
    zoom-state-time-to-live: 30

super-admin:
  email: ${SUPER_ADMIN_EMAIL}
  password: ${SUPER_ADMIN_PASSWORD}

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

server:
  port: 8080