spring:
  application:
    name: bridge-spero
    storage:
      public-dir: ${STATIC_DIR:static/uploads}
      private-dir: ${PRIV_DIR:uploads}
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  datasource:
    url: ${DATASOURCE_URL}
    replicaUrl: ${REPLICA_DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show_sql: ${JPA_SHOWSQL:false}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ${JPA_FORMATSQL:false}
  liquibase:
    change-log: classpath:db/changelog-master.yaml
zoom:
  client-id: ${ZOOM_CLIENT_ID}
  client-secret: ${ZOOM_CLIENT_SECRET}
  redirect-uri: ${ZOOM_REDIRECT_URI}
  webhook-secret: ${ZOOM_WEBHOOK_SECRET}

application:
  security:
    authentication:
      jwt:
        base64-secret: ${JWT_SECRET}
        access-token-validity-in-seconds: 86400 # 1 day
        refresh-token-validity-in-seconds: 604800 # 1 week
  redis:
    address: ${REDIS_ADDRESS}
    connection-pool-size: 4
    connection-minimum-idle-size: 2
    prefix: bs
    token-prefix: bs:token
    token-time-to-live: 604800
    zoom-token-prefix: bs:token:zoom
    zoom-token-time-to-live: 7776000  # 90 days
    zoom-state-prefix: bs:zoom:state
    zoom-state-time-to-live: 30

super-admin:
  email: ${SUPER_ADMIN_EMAIL}
  password: ${SUPER_ADMIN_PASSWORD}

logging:
  level:
    org:
      springframework:
        web: ${LOG_LEVEL:INFO}
        security: ${LOG_LEVEL:INFO}

server:
  port: ${SPRING_PORT:8080}
