spring:
  application:
    name: bridge-spero
  server:
    port: 8081
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: 1234
zoom:
  client-id: ${ZOOM_CLIENT_ID}
  client-secret: ${ZOOM_CLIENT_SECRET}
  redirect-uri: ${ZOOM_REDIRECT_URI}